language: cpp
compiler:
  - gcc
  - clang
before_script:
  - sudo apt-get install libwxgtk2.8-dev libboost-thread1.48-dev libboost-system1.48-dev libboost-filesystem1.48-dev
# optional dependencies
  - sudo apt-get install libboost-test1.48-dev libalure-dev
  - git submodule update --init --recursive
  - cmake -DSPRINGLOBBY_UPDATER:BOOL=ON .
script:
  - make -j2
  - make check
