language: cpp
compiler:
  - gcc
  - clang # disabled, libboost-signals fails to compile: https://travis-ci.org/springlobby/springlobby/jobs/21325986
before_script:
  - sudo add-apt-repository -y ppa:wxformbuilder/wxwidgets
  - sudo add-apt-repository -y ppa:boost-latest/ppa
  - sudo apt-get update
  - sudo apt-cache search libboost
#  - sudo apt-cache search libwxgtk
  - sudo apt-get install libwxgtk3.0-dev libboost-thread1.55-dev libboost-system1.55-dev libboost-filesystem1.55-dev
# optional dependencies
  - sudo apt-get install libboost-test1.55-dev libalure-dev
  - git submodule update --init --recursive
  - cmake -DSPRINGLOBBY_UPDATER:BOOL=ON .
script:
  - make -j2 -k
  - make -k check
